### ISSUE TITLE
No steam games found

### ISSUE THREAD

**Issue by Wirda33** [Novattz/creamlinux-installer#1]
Im just getting "no steam games found on this computer or connected drives"

I do have a bunch of them installed. Hoi4, eu4, ck3 etc.

**Comment by Novattz** [comment]
Could you provide some error logs from console?

**Comment by Wirda33** [comment]
`

  _    _ _   _ _      ____   _____ _  ________ _____  
 | |  | | \ | | |    / __ \ / ____| |/ /  ____|  __ \ 
 | |  | |  \| | |   | |  | | |    | ' /| |__  | |__) |
 | |  | | . ` | |   | |  | | |    |  < |  __| |  _  / 
 | |__| | |\  | |___| |__| | |____| . \| |____| | \ \ 
  \____/|_| \_|______\____/ \_____|_|\_\______|_|  \_\
                                                      
    

    > Made by Tickbase
    > GitHub: https://github.com/Novattz/creamlinux-installer
    > Version: v1.0.0
    
    
No Steam games found on this computer or connected drives.
(deck@steamdeck ~)$ `

**Comment by Wirda33** [comment]
It's just this

[log.txt](https://github.com/user-attachments/files/16199905/log.txt)

**Comment by Novattz** [comment]
Im really unsure if it will work on steamdeck as it wasnt designed for it. I will add some more error handling and look into file system scanning for steamdecks. Ill update the post and you can test it out when i have debugged and maybe found an update.

**Comment by Wirda33** [comment]
Excellent, thank you!

And thanks for all your work

**Comment by Novattz** [comment]
> Excellent, thank you!
> 
> And thanks for all your work

Added a new release. Try now and give me an update.

**Comment by Wirda33** [comment]
Now it's saying it can't find any steam library folders

[log.txt](https://github.com/user-attachments/files/16201463/log.txt)

**Comment by Novattz** [comment]
> Now it's saying it can't find any steam library folders
> 
> path is something like /home/deck/.steam/steam/steamapps/common/
> 
> [log.txt](https://github.com/user-attachments/files/16201463/log.txt)
> 
> edit: In the mean time I was able to install creamlinux manualy for each game, which works like a charm. Still it would be amazing to get this script working on steamdeck to save the hussle of doing it manually for each game :)
> 
> Thank you again

I hope you don't mind testing again. i added more paths and the script will now produce a log file if it fails.

**Comment by Wirda33** [comment]
Quite the opposite actually. Here are the logs 
[log.txt](https://github.com/user-attachments/files/16202956/log.txt)
[script.log](https://github.com/user-attachments/files/16202957/script.log)

**Comment by boofiboi** [comment]
[Try this PR](https://github.com/Novattz/creamlinux-installer/pull/2) Nova is big dumb dumb and includes directories that apply to his computer but not others.

**Comment by boofiboi** [comment]
Disregard my previous comment, I'm the dumb dumb here.


Can you try navigating to /home/deck/.steam/root and seeing if there's anything in there?

**Comment by Novattz** [comment]
Added more logging to the .log file, fixed typos and added support for symlinks. you should be able to find the steam library now. if not provide the .log file along with the path of your steam library.

**Comment by Wirda33** [comment]
I will test this soon and let you know. Thank you
