### ISSUE TITLE
[ Feature Request ] Contributing

### ISSUE THREAD

**Issue by spdforbital** [Novattz/creamlinux-installer#11]
I'd like to contribute and get started on the TODO list.

For matching the files to the DLC ID's, we would have to keep a database hardcoded of the filenames to the appid no? 

Also, creaminstaller got DMCA'd and haven't been able to find on the forks on how it downloaded the DLC files. I tried with login anonymous and steamcmd to download some dlc with no luck. Did it connect to a server that hosted the files or directly on cs rin?  I'd like to not have to host a portal and update manually myself the dlc files if possible. 

Any input is appreciated and let me know with what else I can contribute.

**Comment by Novattz** [comment]
Nah steamapi already provides appid and dlc name. what i was thinking with that was cross referencing dlc ids to already installed/downloaded dlcs. Just haven't gotten around to doing it yet. and just use https://github.com/acidicoala/SmokeAPI same thing just manual work to install.
