### ISSUE TITLE
Error caused by tqdm [BUG]

### ISSUE THREAD

**Issue by JustPotatov2** [Novattz/creamlinux-installer#14]
**Before submitting, have you tried:**
- Using smokeapi with Proton? [ ] Yes [ ✓ ] No
- Checking if `LD_PRELOAD` is blocked on your system? [ ] Yes [ ✓ ] No

**Describe the bug**

It gets an error while launching that says that there is not a tqdm module ( I have installed it ), then I tried making tqdm.py myself and I get past that error, but I get this one.

**Terminal output** 
"
Traceback (most recent call last):
  File "/home/geto/Downloads/DLC/dlc_fetcher.py", line 13, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm' 
"

Then I tried making tqdm.py myself and the new error that I get is this one:

"
Traceback (most recent call last):
  File "/home/geto/Downloads/DLC/dlc_fetcher.py", line 12, in <module>
    from tqdm import tqdm
  File "/home/geto/Downloads/DLC/tqdm.py", line 1, in <module>
    from tqdm import tqdm
ImportError: cannot import name 'tqdm' from partially initialized module 'tqdm' (most likely due to a circular import) (/home/geto/Downloads/DLC/tqdm.py)
"

**Log File Output**

Empty

**Debug Output**
- Run the script with the **`--debug`** argument and attach the log file **`debug_script.log`** to this issue.
Can't run the command for some reason.
**Steam library path**

/home/geto/.local/share/Steam/steamapps/

/media/geto/NVME/SteamLibrary/steamapps/  <-- on this path is the game 

/media/geto/41757c01-2d06-4a7f-8c5f-1e43971b8438/SteamLibrary/steamapps/

**Additional context**
If someone tries to help me I'll be really glad, but just so you know I'm knew to Linux and I'm not the brightest when It comes to Linux. 
If it matters:
CPU: Ryzen 5 5600
GPU: Rc 6700 xt
OS: PikaOS 4 (Debian based)

**Comment by Novattz** [comment]
By creating a tqdm.py file you are overriding the actual tqdm module. This leads to a circular import when python tries to import the module itself. I suggest deleting the file and try downloading the python-tqdm package and running `/usr/bin/python3 dlc_fether.py` (this ensures the use of the system python binary). If that works and something like `python dlc_fetcher.py` doesn't then you likely have something like pyenv that manages your python packages which doesnt make the packages you install system-wide accessible. If both of those options fail your last resort could be the following:

```
python3 -m venv dlc_env
source dlc_env/bin/activate
pip install tqdm requests
python3 /path/to/dlc_fetcher.py
```

**Comment by JustPotatov2** [comment]
With the command below it worked and now I see the problem because I used pipx installing tqdm rather than pip. Okay thanks a bunch for the help.

**Comment by boofiboi** [comment]
thats crazy.
