### ISSUE TITLE
Latest release broken on Linux Mint

### ISSUE THREAD

**Issue by Fireball5939** [Novattz/creamlinux-installer#4]
When I run the installer all I get is the `UNLOCKER` ASCII text art, and no games are listed. There's no error messages either, it's like the program just stops running after it prints it or is stuck in a loop doing nothing.

Another issue I had (On the initial release) was that it wouldn't work at all for Payday 2, though I assume this to be an issue with CreamAPI as using it by itself still didn't work

**Comment by Novattz** [comment]
You should be getting a logfile in the directory that the dlc_fetcher script was launched from. Copy paste the output from terminal that u get and log for log files. also provide the path that your steam library has games in.

**Comment by Fireball5939** [comment]
I don't have a log file at all, and the file path for most of my steam games (Including Payday 2) is `/mnt/Gaymes/SteamLibrary/steamapps/common`, 


  _    _ _   _ _      ____   _____ _  ________ _____  
 | |  | | \ | | |    / __ \ / ____| |/ /  ____|  __ \ 
 | |  | |  \| | |   | |  | | |    | ' /| |__  | |__) |
 | |  | | . ` | |   | |  | | |    |  < |  __| |  _  / 
 | |__| | |\  | |___| |__| | |____| . \| |____| | \ \ 
  \____/|_| \_|______\____/ \_____|_|\_\______|_|  \_\
                                                      
    

    > Made by Tickbase
    > GitHub: https://github.com/Novattz/creamlinux-installer
    > Version: v1.0.4
    
(The ASCII text is a lil messed up on GitHub, but it shows up correctly in the terminal as UNLOCKER)

**Comment by Novattz** [comment]
> I don't have a log file at all, and the file path for most of my steam games (Including Payday 2) is `/mnt/Gaymes/SteamLibrary/steamapps/common`,
> 
> | | | | \ | | | / __ \ / __**| |/ / __**| __ \ | | | | | | | | | | | | | ' /| |** | |**) | | | | | . ` | | | | | | | | < | | | _ / | || | |\ | |**_| |__| | |_**_| . | |__**| | \ \ _**_/|_| _|_**_**_**_/ _**__|_|_______|_| _\
> 
> ```
> > Made by Tickbase
> > GitHub: https://github.com/Novattz/creamlinux-installer
> > Version: v1.0.4
> ```
> 
> (The ASCII text is a lil messed up on GitHub, but it shows up correctly in the terminal as UNLOCKER)

Sorry for such a late reply. I've pushed an update regarding looping and the script should timeout if that happens. ive also added a debug argument so running the script with python dlc_fetcher.py --debug will produce a log file no matter what containing what the script does and doesn't do. Please try it out and provide a log file if the issue isn't fixed.

**Comment by Fireball5939** [comment]
Oh don't worry about a late reply, tis better than no reply at all after all :P 
Anyways, I can confirm that it works now! The only "DLC" I don't have is the Hotline Miami stuff (Sociopath perk deck and the Jacket character) but you need to own another game to get that stuff, so I'm not worried about it.

I did notice a strange behavior in the logs though, 
[debug_script.log](https://github.com/user-attachments/files/16267470/debug_script.log)
Judging by the file paths I'm assuming it's something from my games that use Proton? I think this is from Proton and not the script itself.

**Comment by Novattz** [comment]
> Oh don't worry about a late reply, tis better than no reply at all after all :P Anyways, I can confirm that it works now! The only "DLC" I don't have is the Hotline Miami stuff (Sociopath perk deck and the Jacket character) but you need to own another game to get that stuff, so I'm not worried about it.
> 
> I did notice a strange behavior in the logs though, [debug_script.log](https://github.com/user-attachments/files/16267470/debug_script.log) Judging by the file paths I'm assuming it's something from my games that use Proton? I think this is from Proton and not the script itself.

Yes thats the path for games installed with proton. Glad it worked!
