### ISSUE TITLE
[BUG] Creamlinux not detecting steam install in another drive, even when provided manually

### ISSUE THREAD

**Issue by HambOrig** [Novattz/creamlinux-installer#7]
**Describe the bug**
- The creamlinux installer is not detecting my flatpak steam install located inside the current user's home folder, located in a separate drive from the OS. in another drive, even when provided manually

**Terminal output** 
>

  _    _ _   _ _      ____   _____ _  ________ _____
 | |  | | \ | | |    / __ \ / ____| |/ /  ____|  __ \
 | |  | |  \| | |   | |  | | |    | ' /| |__  | |__) |
 | |  | | . ` | |   | |  | | |    |  < |  __| |  _  /
 | |__| | |\  | |___| |__| | |____| . \| |____| | \ \
  \____/|_| \_|______\____/ \_____|_|\_\______|_|  \_\

    > Made by Tickbase
    > GitHub: https://github.com/Novattz/creamlinux-installer
    > Version: v1.0.5

Error finding Steam library folders: No Steam library folders found.
Scanned paths:
  - /home/hamb/.steam/steam
  - /home/hamb/.local/share/Steam
  - /home/deck/.steam/steam
  - /home/deck/.local/share/Steam
  - /mnt/Jogos/Steam
  - /run/media/mmcblk0p1
Falling back to Manual Method since no library folder was found
Steamapps Path: /home/hamb/.var/app/com.valvesoftware.Steam/.local/share/Steam
Error finding Steam apps: No Steam games found.
Scanned folders:
  - /home/hamb/.var/app/com.valvesoftware.Steam/.local/share/Steam
No Steam games found on this computer or connected drives.
>

**Steam library path**
- /home/hamb/.var/app/com.valvesoftware.Steam/.local/share/Steam

**Additional context**
 - N/A

**Comment by Novattz** [comment]
Updated try again. if it doesnt work run it with debug and provide the file contents inside /Steam.
