### ISSUE TITLE
[BUG] Cities Skylines (1) instantly crashes

### ISSUE THREAD

**Issue by kz-n** [Novattz/creamlinux-installer#8]
**Describe the bug**
Installed creamlinux-installer to Cities-Skylines, game opens the paradox launcher for a second then closes

**Terminal output** 
and 
**Log File Output**
IDK where to find

**Debug Output**
doing that doesn't even start

**Steam library path**
/run/media/kz-n/Games/SteamLibrary

**Additional context**
don't know

**Comment by Novattz** [comment]
most likely a limitation within creamlinux itself. If u run steam through terminal you should get output of what happens when cities skylines crashes. You could provide this and i could try and see what happens but most likely not an issue i can fix.

**Comment by kz-n** [comment]
runnign steam through terminal didn't provide any logs, so i tried to pipe stderr in the game options to afile and got this
```
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 67085 != 67084, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/lib64Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/libsteam_api.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kz-n/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

**Comment by kz-n** [comment]
ive been turning into ratman from portal trying to figure out how to get dlc unlocking to work on linux for this game man, how can i get this to work, native, proton idgaf it just has to work ;-;

**Comment by Novattz** [comment]
> ive been turning into ratman from portal trying to figure out how to get dlc unlocking to work on linux for this game man, how can i get this to work, native, proton idgaf it just has to work ;-;

because native linux and proton isnt the same. Its blocking LD_PRELOAD which is essential for creamlinux to work. Nothing i can do.

**Comment by kz-n** [comment]
ye ik native and proton isn't the same, regardless im saying i really just want it to work
> Forcing it to run through proton and installing smokeapi could work but i do not know as ive never tried.

how can i try this?

**Comment by Novattz** [comment]
game -> properties -> compatability -> Force the use of a specific steam play compatability tool then you look up how to install smokeapi.

**Comment by kz-n** [comment]
![image](https://github.com/user-attachments/assets/9168eab0-6022-4ddd-b7f4-2bd222f00cd5)
i thank you a lot for telling me the fix. However is there really nothing that can be done without proton?

**Comment by Novattz** [comment]
from a dlc perspective? no. LD_PRELOAD is often used to inject a shared library to override functions and system calls used by said game. If a game checks wether a dlc is owned by calling a certain fucntion, LD_PRELOAD could be used to override that function. Its specifically for linux/unix and windows/proton doesn't have a equivalent. Windows modifications and injections are typically done through other means such as dll injection, api hooking or binary patching. On windows games primarly interact with steam through the steam API. The steam API is a set of functions provided by steam to games for various tasks, including checking which DLCs a user owns. SmokeAPI works by directly modifying the steamAPI DLL that the game loads.
