### ISSUE TITLE
After I enter the command to run the game, it opens but doesn't actually start, it says "launch" and then stops.

### ISSUE THREAD

**Issue by RaulKong898** [Novattz/creamlinux-installer#9]
After running the Python script and being instructed to enter `./cream.sh %command%` in the game's launch options on Steam, when I try to run the game, it says "launch," the game doesn't appear, and then it stops.

**Comment by Novattz** [comment]
> After running the Python script and being instructed to enter `./cream.sh %command%` in the game's launch options on Steam, when I try to run the game, it says "launch," the game doesn't appear, and then it stops.

Run steam through terminal `steam` then try and look through logs for the game you are trying to launch. if its a game that blocks LD_PRELOAD then there is nothing i or the developer of creamlinux can do about it. alternative approach is u can run it through proton and installing creamapi/smokeapi as thats the windows equivalent.

**Comment by SoundOfTheSky** [comment]
I have the same issue.
All I see in logs is `Error: libsteam_api.so not found.` before launch. 
Does it mean game blocks LD_PRELOAD?

**Comment by Novattz** [comment]
> I have the same issue. All I see in logs is `Error: libsteam_api.so not found.` before launch. Does it mean game blocks LD_PRELOAD?

if you see something like: `from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.` then yes LD_PRELOAD is getting blocked. Depending on the game you can try smokeapi with proton but success isnt always guaranteed. you just have to try and see if it works.

**Comment by RaulKong898** [comment]
> > After running the Python script and being instructed to enter `./cream.sh %command%` in the game's launch options on Steam, when I try to run the game, it says "launch," the game doesn't appear, and then it stops.
> 
> Run steam through terminal `steam` then try and look through logs for the game you are trying to launch. if its a game that blocks LD_PRELOAD then there is nothing i or the developer of creamlinux can do about it. alternative approach is u can run it through proton and installing creamapi/smokeapi as thats the windows equivalent.


Fossilize INFO: Overriding serialization path: "/home/raulkong898/.local/share/Steam/shader_cache_temp_dir_d3d12_64/fozpipelinesv6/steamapprun_pipeline_cache".
chdir "/home/raulkong898/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64"
ERROR: ld.so: object '/home/raulkong898/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: line 1: ./cream.sh: No such file or directory
Game Recording - would start recording game 227300, but recording for this game is disabled
Adding process 51417 for gameID 227300
Uploaded AppInterfaceStats to Steam
Game Recording - game stopped [gameid=227300]
Removing process 51417 for gameID 227300
chdir "/home/raulkong898/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64"
Game Recording - would start recording game 227300, but recording for this game is disabled
Adding process 51824 for gameID 227300
ERROR: ld.so: object '/home/raulkong898/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/raulkong898/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: ./cream.sh: No such file or directory
Uploaded AppInterfaceStats to Steam
Game Recording - game stopped [gameid=227300]
Removing process 51824 for gameID 227300
[2024-10-21 08:40:27] Background update loop checking for update. . .
[2024-10-21 08:40:27] Checking for available updates...
[2024-10-21 08:40:27] Downloading manifest: https://client-update.fastly.steamstatic.com/steam_client_publicbeta_ubuntu12
[2024-10-21 08:40:27] Manifest download: send request
[2024-10-21 08:40:27] Manifest download: waiting for download to finish
[2024-10-21 08:40:27] Manifest download: finished
[2024-10-21 08:40:27] Download skipped: /steam_client_publicbeta_ubuntu12 version 1729208001, installed version 1729208001, existing pending version 0
[2024-10-21 08:40:27] Nothing to do
reaping pid: 53654 -- steam

"using fedora"

**Comment by RaulKong898** [comment]
Is this Python script only for games running through Proton or is it for native Linux games too?

**Comment by Novattz** [comment]
> Is this Python script only for games running through Proton or is it for native Linux games too?

the script only works for native linux games. I have tried and tested smokeapi running through proton for euro truck simulator 2 and it works. as you can see from your logs you can see it blocks LD_PRELOAD so creamlinux will not work. The native linux build for euro truck simulator 2 is really bad anyways so running it through proton is the best of both worlds in your situation.
